### ISSUE TITLE
RuntimeError: multi-target not supported at /pytorch/aten/src/THCUNN/generic/ClassNLLCriterion.cu:15

### ISSUE THREAD

**Issue by ilovemyminutes** [iloveslowfood/monthlyDacon12#7]
```shell
/content/drive/MyDrive/Colab Notebooks/monthlyDacon12# python3 main.py
Getting Data...
  0%|                                                                                                                                                              | 0/2657 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 108, in <module>
    device=config.device)
  File "main.py", line 83, in train_model
    loss = loss_function(y_pred, y_true)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py", line 962, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 2468, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 2264, in nll_loss
    ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: multi-target not supported at /pytorch/aten/src/THCUNN/generic/ClassNLLCriterion.cu:15
```

**Comment by ilovemyminutes** [comment]
여길 먼저 참고해봄세
https://discuss.pytorch.org/t/runtimeerror-multi-target-not-supported-newbie/10216

**Comment by ilovemyminutes** [comment]
multi-label 문제에 대해 `nn.CrossEntropyLoss()`를 사용할 수 없어서 발생한 문제였다. 이를 해결하기 위해 `nn.BCEWithLogitsLoss`를 사용하였다.
Reference. https://pytorch.org/docs/stable/generated/torch.nn.BCEWithLogitsLoss.html
