### ISSUE TITLE
Unittest: relative import for custom module

### ISSUE THREAD

**Issue by ilovemyminutes** [iloveslowfood/monthlyDacon12#9]
```shell
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/content/drive/MyDrive/Colab Notebooks/monthlyDacon12/test/test_vanilla_cnn.py", line 6, in <module>
    from core.load.load_data import dirtyMNISTDataset
ModuleNotFoundError: No module named 'core'
```

**Comment by ilovemyminutes** [comment]
```shell
/content/drive/MyDrive/Colab Notebooks/monthlyDacon12# python3 unittest -m test/test_pipeline.py
```
unittest를 모듈에 대해(`-m`) 실행하면 문제 없이 구동됨. 또한, 알아둬야할 것은 *현재 디렉토리*를 기준으로 테스트가 구동되는 식이라는 점. test 디렉토리에 접근한 뒤 테스트를 진행했을 경우에는 import 에러가 발생했으나, 패키지의 최상위 디렉토리에서 테스트를 실행했을 경우 커스텀 모듈들이 정상적으로 import되었다
